#pragma once

#include <stdint.h>
#include "uuid.h"

namespace ATT {
  enum opcodes {
    OPCODE_ERROR = 0x01,
    OPCODE_EXCHANGE_MTU_REQUEST = 0x02,
    OPCODE_EXCHANGE_MTU_RESPONSE = 0x03,
    OPCODE_FIND_INFORMATION_REQUEST = 0x04,
    OPCODE_FIND_INFORMATION_RESPONSE = 0x05,
    OPCODE_FIND_TYPE_BY_VALUE_REQUEST = 0x06,
    OPCODE_FIND_TYPE_BY_VALUE_RESPONSE = 0x07,
    OPCODE_READ_BY_TYPE_REQUEST = 0x08,
    OPCODE_READ_BY_TYPE_RESPONSE = 0x09,
    OPCODE_READ_REQUEST = 0x0a,
    OPCODE_READ_RESPONSE = 0x0b,
    OPCODE_READ_BLOB_REQUEST = 0x0c,
    OPCODE_READ_BLOB_RESPONSE = 0x0d,
    OPCODE_READ_MULTIPLE_REQUEST = 0x0e,
    OPCODE_READ_MULTIPLE_RESPONSE = 0x0f,
    OPCODE_READ_BY_GROUP_TYPE_REQUEST = 0x10,
    OPCODE_READ_BY_GROUP_TYPE_RESPONSE = 0x11,
    OPCODE_WRITE_REQUEST = 0x12,
    OPCODE_WRITE_RESPONSE = 0x13,
    OPCODE_WRITE_COMMAND = 0x52,
    OPCODE_SIGNED_WRITE_COMMAND = 0xd2,
    OPCODE_PREPARE_WRITE_REQUEST = 0x16,
    OPCODE_PREPARE_WRITE_RESPONSE = 0x17,
    OPCODE_EXECUTE_WRITE_REQUEST = 0x18,
    OPCODE_EXECUTE_WRITE_RESPONSE = 0x19,
    OPCODE_HANDLE_VALUE_NOTIFICATION = 0x1b,
    OPCODE_HANDLE_VALUE_INDICATION = 0x1d,
    OPCODE_HANDLE_VALUE_CONFIRMATION = 0x1e
  };

  enum error {
    INVALID_HANDLE = 0x01,
    READ_NOT_PERMITTED = 0x02,
    WRITE_NOT_PERMITTED = 0x03,
    INVALID_PDU = 0x04,
    INSUFFICIENT_AUTHENTICATION = 0x05,
    REQUEST_NOT_SUPPORTED = 0x06,
    INVALID_OFFSET = 0x07,
    INSUFFICIENT_AUTHORIZATION = 0x08,
    PREPARE_QUEUE_FULL = 0x09,
    ATTRIBUTE_NOT_FOUND = 0x0a,
    ATTRIBUTE_NOT_LONG = 0x0b,
    INSUFFICIENT_ENCRYPTION_KEY_SIZE = 0x0c,
    INVALID_ATTRIBUTE_VALUE_LENGTH = 0x0d,
    UNLIKELY_ERROR = 0x0e,
    INSUFFICIENT_ENCRYPTION = 0x0f,
    UNSUPPORTED_GROUP_TYPE = 0x10,
    INSUFFICIENT_RESOURCES = 0x11
  };

};
